id: c9e82c9edf914203a77ca243d98ad645
initial_creation_type: ocr
source_metadata:
  volumes:
    8226616f7ec043f68c236f061672a043:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
